name: cs oop scraper

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Set up environment variables
        run: echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run main script
        env:
          MAIL: ${{ secrets.MAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update novosti.md
        id: auto-commit-action

      - name: Delete photo
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: python removephoto.py

      - name: Take photo
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          MAIL: ${{ secrets.MAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python takephoto.py

      - name: Discord bot notification
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          WEBHOOK_MAIN: ${{ secrets.WEBHOOK_MAIN }}
          WEBHOOK_OTHER1: ${{ secrets.WEBHOOK_OTHER1 }}
        run: python discordBOT.py
